on:
  push:
    branches:
         - main
jobs:
  RUNCMD:
    runs-on:
      ubuntu-latest
    steps:
      - name: checkout code
        uses:   actions/checkout@v4
    
      - name: run command
        run: echo "ltm offer will recive today, jay shri swami smarth"
